package org.yann.mybatis3.generator.normal;

public class S0102User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S0102_USER.ID
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S0102_USER.GROUP_ID
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S0102_USER.USERNAME
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S0102_USER.NAME
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S0102_USER.ID
     *
     * @return the value of S0102_USER.ID
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S0102_USER.ID
     *
     * @param id the value for S0102_USER.ID
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S0102_USER.GROUP_ID
     *
     * @return the value of S0102_USER.GROUP_ID
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S0102_USER.GROUP_ID
     *
     * @param groupId the value for S0102_USER.GROUP_ID
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S0102_USER.USERNAME
     *
     * @return the value of S0102_USER.USERNAME
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S0102_USER.USERNAME
     *
     * @param username the value for S0102_USER.USERNAME
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S0102_USER.NAME
     *
     * @return the value of S0102_USER.NAME
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S0102_USER.NAME
     *
     * @param name the value for S0102_USER.NAME
     *
     * @mbg.generated Sun Jan 24 20:48:44 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }
}